#### Day 12: 3 March Tuesday  (Numpy Library , Documentation Reading)

# Day 13: 4 March Wednesday (Numpy Tasks Perform)

In [1]:
import numpy as np

In [2]:
## List
list = [2,3,4,5,6,7,8,9]
list

[2, 3, 4, 5, 6, 7, 8, 9]

In [3]:
## Type of list
type(list)

list

In [20]:
## Array
arry = np.array([2, 3, 4, 5, 6, 7, 8, 9])
arry

array([2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
## Array dimension
arry.ndim

1

In [22]:
## Array type
type(arry)

numpy.ndarray

In [23]:
## Ones func
one = np.ones(5)
one

array([1., 1., 1., 1., 1.])

In [24]:
## Zeros func
zero = np.zeros(6)
zero

array([0., 0., 0., 0., 0., 0.])

In [25]:
## Dtype change
ones = np.ones(4, dtype = "str")
ones

array(['1', '1', '1', '1'], dtype='<U1')

In [26]:
ones = np.ones((2,8))
ones

array([[1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.]])

In [27]:
ones = np.ones((4,8), dtype="float")
ones

array([[1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.]])

In [28]:
zeros = np.zeros((5,8), dtype= "bool")
zeros

array([[False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False]])

In [29]:
## empty func
emp = np.empty((4,7))
emp

array([[6.23042070e-307, 3.56043053e-307, 1.60219306e-306,
        7.56571288e-307, 7.56587584e-307, 1.37961302e-306,
        1.05699242e-307],
       [8.01097889e-307, 1.78020169e-306, 7.56601165e-307,
        1.02359984e-306, 8.90092016e-307, 1.02361342e-306,
        6.89804133e-307],
       [8.90104239e-307, 8.90098127e-307, 8.90111708e-307,
        6.23054633e-307, 9.34598926e-307, 1.42417629e-306,
        1.11260687e-306],
       [9.34593493e-307, 1.33511290e-306, 1.33511969e-306,
        2.22523140e-306, 6.23059726e-307, 1.33511562e-306,
        6.89805151e-307]])

In [30]:
## arg func
arg = np.arange(3,13)
arg

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [31]:
arge = np.arange(0,13,4)
arge

array([ 0,  4,  8, 12])

In [32]:
## linspace func
ln = np.linspace(2, 12, 18)
ln

array([ 2.        ,  2.58823529,  3.17647059,  3.76470588,  4.35294118,
        4.94117647,  5.52941176,  6.11764706,  6.70588235,  7.29411765,
        7.88235294,  8.47058824,  9.05882353,  9.64705882, 10.23529412,
       10.82352941, 11.41176471, 12.        ])

In [2]:
## Array
arr1 = np.array([2,3,4,5,6,7,8,9,10,11,12,13,14,15,16])
arr1

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

In [3]:
type(arr1)

numpy.ndarray

In [7]:
## 1D convert to 2D
arr2 = arr1.reshape(3, 5)
arr2

array([[ 2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16]])

In [9]:
## 1D convert to 3D
arr3 = arr1.reshape(1,3,5)
arr3

array([[[ 2,  3,  4,  5,  6],
        [ 7,  8,  9, 10, 11],
        [12, 13, 14, 15, 16]]])

In [36]:
##3D convert to 2D
arr2d = arr3.reshape(3,5)
arr2d

array([[ 2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16]])

In [38]:
## 3D convert to 1D
arr1d = arr3.reshape(15)
arr1d

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

In [11]:
arr3.ravel()

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

In [12]:
arr3.flatten()

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

In [13]:
arr3.transpose()

array([[[ 2],
        [ 7],
        [12]],

       [[ 3],
        [ 8],
        [13]],

       [[ 4],
        [ 9],
        [14]],

       [[ 5],
        [10],
        [15]],

       [[ 6],
        [11],
        [16]]])

In [14]:
arry1= np.array([1,3,5,7,9])
arry2 = np.array([2,4,6,8,10])
np.add(arry1,arry2)

array([ 3,  7, 11, 15, 19])

In [16]:
np.subtract(arry2,arry1)

array([1, 1, 1, 1, 1])

In [17]:
np.multiply(arry2,arry1)

array([ 2, 12, 30, 56, 90])

In [18]:
np.divide(arry2, arry1)

array([2.        , 1.33333333, 1.2       , 1.14285714, 1.11111111])

In [19]:
np.dot(arry1,arry2)

np.int64(190)

In [21]:
arry1.max(axis=0)

np.int64(9)

In [24]:
arr2.max(axis = 1)

array([ 6, 11, 16])

In [25]:
arry1.min(axis = 0)

np.int64(1)

In [27]:
arr2.min(axis = 1)

array([ 2,  7, 12])

In [28]:
np.argmax(arry1)

np.int64(4)

In [29]:
np.argmin(arry2)

np.int64(0)

In [30]:
## square root of array
np.sqrt(arry2)

array([1.41421356, 2.        , 2.44948974, 2.82842712, 3.16227766])

In [31]:
## mean
np.mean(arry1)

np.float64(5.0)

In [33]:
## Standard deviation on array
np.std(arry2)

np.float64(2.8284271247461903)

In [34]:
## log func on array
np.log(arry1)

array([0.        , 1.09861229, 1.60943791, 1.94591015, 2.19722458])

In [35]:
## log10 func on array
np.log10(arry1)

array([0.        , 0.47712125, 0.69897   , 0.84509804, 0.95424251])

In [39]:
## 1D array
arr1D= np.array([12,13,14,15,16,17,18,19,20,21,22])
arr1D

array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22])

In [40]:
## 1D array Indexing
arr1D[3]

np.int64(15)

In [41]:
## 1D array Slicing
arr1D[2:6]

array([14, 15, 16, 17])

In [58]:
## 2D array 
arr2D = np.array([[2,3,4,5,6,7]])
arr2D = arr2D.reshape(2,3)
arr2D


array([[2, 3, 4],
       [5, 6, 7]])

In [59]:
type(arr2D)

numpy.ndarray

In [60]:
arr2D.ndim

2

In [61]:
print(arr2D)

[[2 3 4]
 [5 6 7]]


In [64]:
## 2D array Indexing
arr2D[1,2]

np.int64(7)

In [65]:
## 2D array Slicing
arr2D[1:3]

array([[5, 6, 7]])

In [66]:
## 3D array 
arr3D = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18])
arr3D = arr3D.reshape(3,3,2)
arr3D

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]],

       [[13, 14],
        [15, 16],
        [17, 18]]])

In [79]:
## 3D array Indexing
arr3D[2, 2]

array([17, 18])

In [80]:
## 3D array Slicing
arr3D[1,1,1:2]

array([10])